function RGBtoHSV(imageRGB)
    imageHSV = rgb2hsv(imageRGB);
    colorPalette = hsv(256);
    figure, subplot(2,3,1), imshow(imageRGB), title('Image RGB'),...
    subplot(2,3,2), imshow(imageHSV), title('Image HSV'),...
    subplot(2,3,4), imhist(imageHSV(:,:,1),colorPalette ), title('Color'),...
    subplot(2,3,5), imhist(imageHSV(:,:,2)), title('Saturation'),...
    subplot(2,3,6), imhist(imageHSV(:,:,3)), title('Brightness');
end 

