function showHistograms(image)
    figure, subplot(2,3,2), imshow(image), title('Image RGB'),...
    subplot(2,3,4), imhist(image(:,:,1)), title('Red'),...
    subplot(2,3,5), imhist(image(:,:,2)), title('Green'),...
    subplot(2,3,6), imhist(image(:,:,3)), title('Blue');
end